ERROR: Ошибка
Traceback (most recent call last):
  File "D:\pythonProject\variable\tests_12_4.py", line 84, in test_run
    r2 = Runner(123, 10)
         ^^^^^^^^^^^^^^^
  File "D:\pythonProject\variable\tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
WARNING: Неверный тип данных для объекта Runner
ERROR: Ошибка
Traceback (most recent call last):
  File "D:\pythonProject\variable\tests_12_4.py", line 75, in test_walk
    r1 = Runner("John", -5)
         ^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject\variable\tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
WARNING: Неверная скорость для Runner
